name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Print deployment message
        run: echo "deploying to production"

      - name: Mark deployment as successful
        run: echo "Deployment to prod successful!"

      - name: Send deployment to Swarmia
        if: success()
        run: |
          JSON_STRING=$( jq --null-input --compact-output \
            --arg version "v1.0" \
            --arg appName "test-app3" \
            --arg environment "production" \
            --arg commitSha "${{ github.sha }}" \
            --arg repositoryFullName "${{ github.repository }}" \
            '{"version": $version, "appName": $appName, "environment": $environment, "commitSha": $commitSha, "repositoryFullName": $repositoryFullName}' )    
            echo $JSON_STRING
            curl -H "Authorization: ${{ secrets.SWARMIA_DEPLOYMENTS_AUTHORIZATION }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_STRING" \
            https://hook.swarmia.com/deployments
  
  
